name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: secrets
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: 'false'

    - name: Make envfile be
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_API: ${{ secrets.API }}
        envkey_DATABASE: ${{ secrets.DATABASE }}
        envkey_DATABASE_FILE: ${{ secrets.DATABASE_FILE }}
        envkey_DATABASE_FILE_DB: ${{ secrets.DATABASE_FILE_DB }}
        envkey_KEY_ID: ${{ secrets.KEY_ID }}
        envkey_KEY_SECRET: ${{ secrets.KEY_SECRET }}
        envkey_PORT: ${{ secrets.PORT }}
        directory: exam-proctor-be
        file_name: .env

    - name: Make envfile fe
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_BACKEND: ${{ secrets.REACT_APP_BACKEND }}
        envkey_KEY_ID: ${{ secrets.KEY_ID }}
        directory: exam-proctor-fe
        file_name: .env
        

    - name: docker-compose down 
      run: docker-compose down
    
    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose up
      run: docker-compose up  
