name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: 'Create env file be'
      run: |
        touch exam-proctor-be/.env
        echo API=${{ secrets.API }} >> exam-proctor-be/.env
        echo DATABASE=${{ secrets.DATABASE }} >> exam-proctor-be/.env
        echo DATABASE_FILE=${{ secrets.DATABASE_FILE }} >> exam-proctor-be/.env
        echo DATABASE_FILE_DB=${{ secrets.DATABASE_FILE_DB }} >> exam-proctor-be/.env
        echo KEY_ID=${{ secrets.KEY_ID }} >> exam-proctor-be/.env
        echo KEY_SECRET=${{ secrets.KEY_SECRET }} >> exam-proctor-be/.env
        echo PORT=${{ secrets.PORT }} >> exam-proctor-be/.env
        echo SECRET=${{ secrets.SECRET }} >> exam-proctor-be/.env
        cat exam-proctor-be/.env

    - name: 'Create env file be-1'
      run: |
        touch exam-proctor-be-lb1/.env
        echo API=${{ secrets.API }} >> exam-proctor-be-lb1/.env
        echo DATABASE=${{ secrets.DATABASE }} >> exam-proctor-be-lb1/.env
        echo DATABASE_FILE=${{ secrets.DATABASE_FILE }} >> exam-proctor-be-lb1/.env
        echo DATABASE_FILE_DB=${{ secrets.DATABASE_FILE_DB }} >> exam-proctor-be-lb1/.env
        echo KEY_ID=${{ secrets.KEY_ID }} >> exam-proctor-be-lb1/.env
        echo KEY_SECRET=${{ secrets.KEY_SECRET }} >> exam-proctor-be-lb1/.env
        echo PORT=${{ secrets.PORT1 }} >> exam-proctor-be-lb1/.env
        echo SECRET=${{ secrets.SECRET }} >> exam-proctor-be-lb1/.env
        cat exam-proctor-be-lb1/.env

    - name: 'Create env file fe'
      run: |
        touch exam-proctor-be/.env
        echo KEY_ID=${{ secrets.KEY_ID }} >> exam-proctor-fe/.env
        echo REACT_APP_BACKEND=${{ secrets.REACT_APP_BACKEND }} >> exam-proctor-fe/.env
        cat exam-proctor-be/.env

    - name: docker-compose down 
      run: docker-compose down
    
    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose up -d
      run: docker-compose up -d
