name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'false'

    - name: docker-compose down 
      run: docker-compose down
    
    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose up
      run: docker-compose up  
