name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: 'false'

    - name: 'Create env file'
      run: |
        touch .env
        echo API=${{ secrets.API }} >> .env
        echo DATABASE=${{ secrets.DATABASE }} >> .env
        echo DATABASE_FILE=${{ secrets.DATABASE_FILE }} >> .env
        echo DATABASE_FILE_DB=${{ secrets.DATABASE_FILE_DB }} >> .env
        echo KEY_ID=${{ secrets.KEY_ID }} >> .env
        echo KEY_SECRET=${{ secrets.KEY_SECRET }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo REACT_APP_BACKEND=${{ secrets.REACT_APP_BACKEND }} >> .env
        cat .env

    - name: docker-compose down 
      run: docker-compose down
    
    - name: docker-compose build
      run: docker-compose build

    - name: docker-compose up
      run: docker-compose up  
